#!/bin/sh

git_update() {
	url=$1
	branch=$2
	path=$3

	if [ ! -d $path ]; then
		echo "Cloning $url at $branch"
		git clone -q $url -b $branch $path
	else
		echo "Updating $url at $branch"
		(cd $path && git fetch -q && git checkout -qB $branch origin/$branch)
	fi
}

sphinx_update() {
	doc=$1
	dest=$2
	symlink=$3
	draft=$4
	pdf=$5
	ebook=$6

	if [ -d $1/build ]; then
		echo "Removing previous build"
		rm -r $1/build
	fi

	if [ "$draft" != "no" ]; then
		DRAFTOPTS="-t draft"
	fi

	echo Building HTML $doc
	(cd $doc && make singlehtml SPHINXOPTS="$DRAFTOPTS")
	rm -rf $dest
	cp -r $doc/build/singlehtml $dest

	if [ "$pdf" = "yes" ]; then
		(cd $1 && make latexpdf SPHINXOPTS="$DRAFTOPTS")
		rm $doc/build/latex/blockdiag-*.pdf
		for p in `ls -1 $doc/build/latex/*.pdf`; do
			cp $p $dest/`basename $p | sed 's,\.pdf$,-view.pdf,g'`
		done

		(cd $1 && make latexpdf SPHINXOPTS="$DRAFTOPTS -t lettertwoside")
		rm $doc/build/latex/blockdiag-*.pdf
		for p in `ls -1 $doc/build/latex/*.pdf`; do
			cp $p $dest/`basename $p | sed 's,\.pdf$,-print-letter.pdf,g'`
		done

		(cd $1 && make latexpdf SPHINXOPTS="$DRAFTOPTS -t a4twoside")
		rm $doc/build/latex/blockdiag-*.pdf
		for p in `ls -1 $doc/build/latex/*.pdf`; do
			cp $p $dest/`basename $p | sed 's,\.pdf$,-print-a4.pdf,g'`
		done
	fi

	if [ "$ebook" = "yes" ]; then
		(cd $1 && make epub SPHINXOPTS="$DRAFTOPTS")
		cp $doc/build/epub/*.epub $dest
	fi

	echo Updating $dest
	git add $dest
	git commit -m"Update $dest" -s $dest

	if [ "$symlink" = "yes" ]; then
		(cd $(dirname $dest) && rm -f current && ln -s $(basename $dest) current)
		git add $(dirname $dest)/current
		git commit -qm"Set $dest as current" -s $(dirname $dest)/current
	fi
}

tmp=$(pwd)/tmp

### Release Notes

# Fido
git_update https://github.com/Freescale/Documentation.git fido $tmp/docs
sphinx_update $tmp/docs/release-notes doc/release-notes/1.8 no no yes

# Jethro
git_update https://github.com/Freescale/Documentation.git jethro $tmp/docs
sphinx_update $tmp/docs/release-notes doc/release-notes/2.0 yes no yes

### User Guide

# Master
git_update https://github.com/Freescale/Documentation.git master $tmp/docs
sphinx_update $tmp/docs/user-guide doc/user-guide/1.6 yes

### FAQ

# Master
git_update https://github.com/Freescale/Documentation.git master $tmp/docs
sphinx_update $tmp/docs/FAQ doc/faq
